services:
  - type: web
    name: purdue-mbb-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python collect.py
    startCommand: |
      gunicorn server:app --workers=2 --threads=4 --timeout=120 --bind 0.0.0.0:$PORT
    autoDeploy: true
